version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000"  # TCP
    environment:
      CLICKHOUSE_USER: "asalin"
      CLICKHOUSE_PASSWORD: "12345678"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init/:/docker-entrypoint-initdb.d/ 

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - clickhouse
    environment:
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USERNAME: "asalin"
      CLICKHOUSE_PASSWORD: "12345678"
    ports:
      - "8000:8000"

volumes:
  clickhouse_data:
